In [1]:
import numpy as np

# Arange

In [2]:
# Crear una lista hasta de 0 a 10 de dos en dos
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# Zeros

In [4]:
# Matriz de ceros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

# Ones

In [5]:
# Matriz de unos
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# Linspace

In [9]:
# 200 datos de cero a 10 con una distacia igual
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Matriz identidad

In [11]:
# Matriz identidad 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Generar valores aleatorios

In [13]:
# me genera 3 numeors aleatorios con valores entre 0 y uno
np.random.rand(3)

array([0.46312694, 0.72026572, 0.67296272])

# Generar un entero aleatorio

In [16]:
# Generara una matriz 3 x 3 de numeros aleatorio entre 1 y 20
np.random.randint(1,20,(3,3))

array([ 1, 16, 10])