In [1]:
import numpy as np
array = np.random.randint(1,20,(2,6))
array

array([[12, 18, 17, 10, 15,  9],
       [ 2,  5, 12, 18, 17,  1]])

# Numero más grande

In [2]:
# Maximo del arreglo
array.max()

# Me trae el maximo de cada columna
array.max(axis=0)

# Me trae el maximo de cada fila
array.max(axis=1)

array([18, 18])

# Retornar el indice del numero mas grande

In [3]:
# Maximo del arreglo
array.argmax()

# Me trae el maximo de cada columna
array.argmax(axis=0)

# Me trae el maximo de cada fila
array.argmax(axis=1)

array([1, 3])

# Número más pequeño

In [4]:
# Minimo del arreglo
array.min()

# Me trae el minimo de cada columna
array.min(axis=0)

# Me trae el minimo de cada fila
array.min(axis=1)

array([9, 1])

# Retornar el indice del numero mas pequeño

In [5]:
# Minimo del arreglo
array.argmin()

# Me trae el minimo de cada columna
array.argmin(axis=0)

# Me trae el minimo de cada fila
array.argmin(axis=1)

array([5, 5])

# Rango del arreglo

In [6]:
# rango del arreglo
array.ptp()

# Me trae el rango de cada columna
array.ptp(axis=0)

# Me trae el rango de cada fila
array.ptp(axis=1)

array([ 9, 17])

# Hallar un percentil dentro de mi arreglo

In [7]:
np.percentile(array, q=1)

1.11

# Ordenar el arreglo

In [8]:
array.sort()

# Hallar la media

In [9]:
array.mean()

11.333333333333334

# Calcular la mediana

In [12]:
np.median(array)

12.0

# Desviación estandar

In [ ]:
np.std(array)

# Varianza

In [13]:
np.var(array)

34.05555555555556

# Concatenar dos arreglos

In [15]:
np.concatenate([[1,2,3],[4,5,6]])

array([1, 2, 3, 4, 5, 6])