# Es

Es el principal objeto de la libreria:  
- Representa los datos de forma ordenada.
- Es indexado.
- Se puede acceder a uno o grupo de datos.

# Definición

In [2]:
import numpy as np

list = [1,2,3,4,5]
array = np.array(list)

print(type(array))

<class 'numpy.ndarray'>


# Array de multiples dimesiones

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(matrix)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Acceder a los elementos de array

In [21]:
# Retornar el primer valor, iniciando desde 0
array[0]

# Acceder a los primeros tres valores
array[:3]

# Acceder a los primeros tres valores dando un paso de tamaño 2
array[::2]

# Acceder al último valor
array[-1]

# ====================

# Retornar valores de matrices
# Primera fila
array2[0]

# Primer valor de la primera fila
array2[0, 0]

# Traer desde la segunda fila
array2[1:]

# Traer desde la segunda fila, las primeras dos columnas
array2[1:, :2]


primer valor 1
acceder a los primeros tres valores [1 2 3]
acceder a los primeros tres valores dando un paso de tamaño 2 [1 3 5]
acceder al ultimo valor 5
primera fila [1 2 3]
primer valor de la primera fila 1
traer desde la segunda fila [[4 5 6]
 [7 8 9]]
traer desde la segunda fila, las primeras dos columnas [[4 5]
 [7 8]]
